IF COL_LENGTH('dbo.VERSAMENTI_APP', 'NO_RECEIPT_FLAG') IS NULL
BEGIN
    ALTER TABLE dbo.VERSAMENTI_APP
    ADD NO_RECEIPT_FLAG BIT NOT NULL CONSTRAINT DF_VERSAMENTI_APP_NO_RECEIPT_FLAG DEFAULT (0);
END;

IF COL_LENGTH('dbo.VERSAMENTI_APP', 'LOST_RECEIPT_FLAG') IS NULL
BEGIN
    ALTER TABLE dbo.VERSAMENTI_APP
    ADD LOST_RECEIPT_FLAG BIT NOT NULL CONSTRAINT DF_VERSAMENTI_APP_LOST_RECEIPT_FLAG DEFAULT (0);
END;
