IF OBJECT_ID('dbo.FINANCE_STORE_CODE_CATALOG', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.FINANCE_STORE_CODE_CATALOG (
    CodeId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CodeValue NVARCHAR(50) NOT NULL,
    SourceLabel NVARCHAR(255) NULL,
    NormalizedLabel NVARCHAR(255) NULL,
    SeedSource NVARCHAR(100) NULL,
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_FINANCE_STORE_CODE_CATALOG_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_FINANCE_STORE_CODE_CATALOG_UpdatedAt DEFAULT SYSUTCDATETIME()
  );
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_FINANCE_STORE_CODE_CATALOG_CodeValue'
    AND object_id = OBJECT_ID('dbo.FINANCE_STORE_CODE_CATALOG')
)
BEGIN
  CREATE UNIQUE INDEX UX_FINANCE_STORE_CODE_CATALOG_CodeValue
  ON dbo.FINANCE_STORE_CODE_CATALOG(CodeValue);
END
GO

IF OBJECT_ID('dbo.FINANCE_STORE_CODE_ASSIGNMENTS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.FINANCE_STORE_CODE_ASSIGNMENTS (
    AssignmentId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CodeValue NVARCHAR(50) NOT NULL,
    StoreCode NVARCHAR(20) NOT NULL,
    ValidFrom DATE NOT NULL,
    Note NVARCHAR(255) NULL,
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_FINANCE_STORE_CODE_ASSIGNMENTS_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_FINANCE_STORE_CODE_ASSIGNMENTS_UpdatedAt DEFAULT SYSUTCDATETIME()
  );
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_FINANCE_STORE_CODE_ASSIGNMENTS_CodeValue_ValidFrom'
    AND object_id = OBJECT_ID('dbo.FINANCE_STORE_CODE_ASSIGNMENTS')
)
BEGIN
  CREATE UNIQUE INDEX UX_FINANCE_STORE_CODE_ASSIGNMENTS_CodeValue_ValidFrom
  ON dbo.FINANCE_STORE_CODE_ASSIGNMENTS(CodeValue, ValidFrom);
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_FINANCE_STORE_CODE_ASSIGNMENTS_CodeValue'
    AND object_id = OBJECT_ID('dbo.FINANCE_STORE_CODE_ASSIGNMENTS')
)
BEGIN
  CREATE INDEX IX_FINANCE_STORE_CODE_ASSIGNMENTS_CodeValue
  ON dbo.FINANCE_STORE_CODE_ASSIGNMENTS(CodeValue, ValidFrom DESC);
END
GO
