IF OBJECT_ID('dbo.ORARI_VISIBLE_PEOPLE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ORARI_VISIBLE_PEOPLE (
    VisibilityId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    StoreCode NVARCHAR(20) NOT NULL,
    WeekStart DATE NOT NULL,
    VisibleNamesJson NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_ORARI_VISIBLE_PEOPLE_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_ORARI_VISIBLE_PEOPLE_UpdatedAt DEFAULT SYSUTCDATETIME()
  );
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_ORARI_VISIBLE_PEOPLE_StoreCode_WeekStart'
    AND object_id = OBJECT_ID('dbo.ORARI_VISIBLE_PEOPLE')
)
BEGIN
  CREATE UNIQUE INDEX UX_ORARI_VISIBLE_PEOPLE_StoreCode_WeekStart
  ON dbo.ORARI_VISIBLE_PEOPLE(StoreCode, WeekStart);
END
GO
