IF OBJECT_ID('dbo.VERSAMENTI_FINANCE_MATCH', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.VERSAMENTI_FINANCE_MATCH (
        MatchId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        AppRecordKey NVARCHAR(200) NOT NULL,
        AppRecordId NVARCHAR(100) NULL,
        AppStore NVARCHAR(50) NULL,
        FinanceVersamentoId INT NOT NULL,
        SlotNo TINYINT NOT NULL,
        MatchScore DECIMAL(5,2) NULL,
        MatchSource NVARCHAR(20) NOT NULL CONSTRAINT DF_VERS_FIN_MATCH_SOURCE DEFAULT ('manual'),
        CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_VERS_FIN_MATCH_CREATED DEFAULT (SYSDATETIME()),
        UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_VERS_FIN_MATCH_UPDATED DEFAULT (SYSDATETIME())
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.VERSAMENTI_FINANCE_MATCH')
      AND name = 'UQ_VERS_FIN_MATCH_APP_SLOT'
)
BEGIN
    CREATE UNIQUE INDEX UQ_VERS_FIN_MATCH_APP_SLOT
        ON dbo.VERSAMENTI_FINANCE_MATCH (AppRecordKey, SlotNo);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.VERSAMENTI_FINANCE_MATCH')
      AND name = 'UQ_VERS_FIN_MATCH_FINANCE_ID'
)
BEGIN
    CREATE UNIQUE INDEX UQ_VERS_FIN_MATCH_FINANCE_ID
        ON dbo.VERSAMENTI_FINANCE_MATCH (FinanceVersamentoId);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.VERSAMENTI_FINANCE_MATCH')
      AND name = 'IX_VERS_FIN_MATCH_APP_KEY'
)
BEGIN
    CREATE INDEX IX_VERS_FIN_MATCH_APP_KEY
        ON dbo.VERSAMENTI_FINANCE_MATCH (AppRecordKey);
END
GO
