IF OBJECT_ID('dbo.RENDICONTO_VERIFICHE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RENDICONTO_VERIFICHE (
        id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        row_uuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        record_key NVARCHAR(64) NOT NULL,
        record_kind NVARCHAR(20) NOT NULL,
        site NVARCHAR(20) NOT NULL,
        verificato BIT NOT NULL CONSTRAINT DF_RENDICONTO_VERIFICHE_VERIFICATO DEFAULT 0,
        nota NVARCHAR(2000) NULL,
        created_at DATETIME2(0) NOT NULL CONSTRAINT DF_RENDICONTO_VERIFICHE_CREATED DEFAULT SYSDATETIME(),
        updated_at DATETIME2(0) NOT NULL CONSTRAINT DF_RENDICONTO_VERIFICHE_UPDATED DEFAULT SYSDATETIME()
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_RENDICONTO_VERIFICHE_RECORD_KEY'
      AND object_id = OBJECT_ID('dbo.RENDICONTO_VERIFICHE')
)
BEGIN
    CREATE UNIQUE INDEX UX_RENDICONTO_VERIFICHE_RECORD_KEY
        ON dbo.RENDICONTO_VERIFICHE(record_key);
END
GO
