IF OBJECT_ID('dbo.DISTINTA_CASSA_CONVALIDE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DISTINTA_CASSA_CONVALIDE (
        id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        row_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_DISTINTA_CASSA_CONVALIDE_ROW_UUID DEFAULT NEWID(),
        site NVARCHAR(50) NOT NULL,
        dal DATE NOT NULL,
        al DATE NOT NULL,
        total_diff DECIMAL(18,2) NOT NULL CONSTRAINT DF_DISTINTA_CASSA_CONVALIDE_TOTAL_DIFF DEFAULT 0,
        created_by NVARCHAR(255) NULL,
        created_name NVARCHAR(255) NULL,
        created_role NVARCHAR(50) NULL,
        created_at DATETIME2(0) NOT NULL CONSTRAINT DF_DISTINTA_CASSA_CONVALIDE_CREATED_AT DEFAULT SYSDATETIME()
    );
END
GO

IF COL_LENGTH('dbo.DISTINTA_CASSA_CONVALIDE', 'total_diff') IS NULL
BEGIN
    ALTER TABLE dbo.DISTINTA_CASSA_CONVALIDE
        ADD total_diff DECIMAL(18,2) NOT NULL CONSTRAINT DF_DISTINTA_CASSA_CONVALIDE_TOTAL_DIFF_ALTER DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.DISTINTA_CASSA_CONVALIDE', 'created_name') IS NULL
BEGIN
    ALTER TABLE dbo.DISTINTA_CASSA_CONVALIDE
        ADD created_name NVARCHAR(255) NULL;
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.DISTINTA_CASSA_CONVALIDE')
      AND name = 'IX_DISTINTA_CASSA_CONVALIDE_SITE_DATES'
)
BEGIN
    CREATE INDEX IX_DISTINTA_CASSA_CONVALIDE_SITE_DATES
        ON dbo.DISTINTA_CASSA_CONVALIDE(site, dal, al);
END
GO
