IF OBJECT_ID(N'dbo.DISTINTA_CASSA_IPRATICO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DISTINTA_CASSA_IPRATICO (
        row_uuid UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_ROW_UUID DEFAULT NEWID(),
        site NVARCHAR(50) NOT NULL,
        data_iso DATE NOT NULL,
        vendite_lorde DECIMAL(18,2) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_VL DEFAULT (0),
        annullati DECIMAL(18,2) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_AN DEFAULT (0),
        scontrini INT NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_SC DEFAULT (0),
        pos DECIMAL(18,2) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_POS DEFAULT (0),
        contanti DECIMAL(18,2) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_CONT DEFAULT (0),
        ticket DECIMAL(18,2) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_TIC DEFAULT (0),
        satispay DECIMAL(18,2) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_SAT DEFAULT (0),
        imported_json NVARCHAR(MAX) NULL,
        mapped_json NVARCHAR(MAX) NULL,
        save_origin NVARCHAR(30) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_ORIGIN DEFAULT (N'auto_on_save'),
        imported_manually BIT NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_MAN DEFAULT ((0)),
        created_at DATETIME2(0) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_CREATED DEFAULT SYSUTCDATETIME(),
        updated_at DATETIME2(0) NOT NULL
            CONSTRAINT DF_DISTINTA_CASSA_IPRATICO_UPDATED DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_DISTINTA_CASSA_IPRATICO PRIMARY KEY CLUSTERED (row_uuid),
        CONSTRAINT UQ_DISTINTA_CASSA_IPRATICO_SITE_DAY UNIQUE (site, data_iso)
    );

    CREATE INDEX IX_DISTINTA_CASSA_IPRATICO_SITE_DATE
        ON dbo.DISTINTA_CASSA_IPRATICO (site, data_iso);
END;
GO
